server:
  port: 10808
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-center?characterEncoding=utf-8&useUnicode=true
    username: dev-user-center
    password: 8]7u2.`.9A0X
    driver-class-name: com.mysql.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
mybatis-plus:
  mapper-locations: classpath:javis/app/web/dao/impl/*.xml
  type-aliases-package: javis.app.web.entity.po

