server:
  port: 10808
  servlet:
    context-path: /user-center
spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/user-center?characterEncoding=utf-8&useUnicode=true&useSSL=false
      username: dev-user-center
      password: 8]7u2.`.9A0X
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
    url: jdbc:mysql://localhost:3306/user-center?characterEncoding=utf-8&useUnicode=true&useSSL=false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null
  profiles:
    active: dev
mybatis-plus:
  mapper-locations: classpath:javis/app/web/dao/impl/*.xml
  type-aliases-package: javis.app.web.entity.po
  global-config:
    refresh-mapper: true
logging:
  config: classpath:log4j2.xml